default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: medium_development

test:
  <<: *default
  database: medium_test

production:
  <<: *default
  database: medium_production
  username: medium
  password: <%= ENV["MEDIUM_DATABASE_PASSWORD"] %>
